[build]  # This is fine if your platform requires it, but it might need refinement.
  command = "waitress-serve --port=8000 app:app"  # Replace with your WSGI command

[[redirects]]
  from = "/*"
  to = "/"  # Allow the Flask app to handle routes
  status = 200
