# Netlify configuration for FastAPI app
[build]
  # No build command needed for FastAPI
  publish = "static"

[dev]
  command = "uvicorn main:app --reload --host=0.0.0.0 --port=8888"
  port = 8888
  targetPort = 50100

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
