[build]
  publish = "static"  # This is fine if your platform requires it, but it might need refinement.
  command = "gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app"  # Replace with your WSGI command

[[redirects]]
  from = "/*"
  to = "/"  # Allow the Flask app to handle routes
  status = 200
